allowBuilds:
  edgedriver: true
  esbuild: true
  geckodriver: true
  msw: true
  protobufjs: true
  snyk: true

overrides:
  'protobufjs@^7': '^7.6.5'
  'uuid@^9': '^14.0.0'
  'ws@^8': '^8.21.0'

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@ckeditor/*'
  - '@cksource/*'
  - '*ckeditor5*'

shellEmulator: true
shamefullyHoist: true
preferFrozenLockfile: true
verifyDepsBeforeRun: false
